spring.application.name=predictions
spring.datasource.url=jdbc:mysql://root:yikyOjaLbMXrfFBCloecxUDQBZQtOoZH@acela.proxy.rlwy.net:53538/railway
spring.datasource.username=root
spring.datasource.password=yikyOjaLbMXrfFBCloecxUDQBZQtOoZH
server.port=8081


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.address=0.0.0.0